### ISSUE TITLE
TurnOff HotSpot

### ISSUE THREAD

**Issue by tarokeitaro** [AlienWolfX/UZ801-USB_MODEM#14]
Hi, how to turn off the hotspot service?
im only use the usb without hotspot.
i think if i turn off the hotspot, the temperature's modems isn't really hot.

**Comment by AlienWolfX** [comment]
> Hi, how to turn off the hotspot service?

Hello @tarokeitaro, 

Using adb:

`adb shell settings wifi setSupplicantEnabled false`

Using adbcontrol:

Run adb control: `java -jar adbcontrol.jar`

And go to settings there you will find mobile hotspot and untik it.

Best regards,
Allen

**Comment by tarokeitaro** [comment]
is it permanent?
so if the modem is restarted, will the hotspot remain off or will it be turn off manually?
