### ISSUE TITLE
I found a new device that can run this version of OpenWRT!

### ISSUE THREAD

**Issue by samthelion17** [AlienWolfX/UZ801-USB_MODEM#15]
I'm unsure if this is the right place to put it but here it goes:

I found [this device](https://www.aliexpress.us/item/3256806674518599.html) on AliExpress and looking at the specifications I noticed that it uses the same chip as the USB sticks, So I bought it, dumped the stock firmware (adb is enabled from the factory, but the device is not rooted) and immediately flashed [openstick](https://wvthoog.nl/openstick/). To my surprise it didn't work, I was stuck on the bootloader, so I decided to flash your version of OpenWRT and Voilà! A tiny (not so tiny) battery-powered device that can run OpenWRT for $20!

Anyways, If you find this as interesting as I did and want more information about the device just let me know and I'll post it here or somewhere else.
![image](https://github.com/user-attachments/assets/e906b956-8f7a-4c93-b530-4377250aafb2)
![IMG_20241122_204730327~2](https://github.com/user-attachments/assets/bb4abf65-e77d-4b6b-887f-9cecba362372)
![IMG_20241122_204642040](https://github.com/user-attachments/assets/bf0ea140-f6e8-40c4-a2db-e42a58b9ad51)

**Comment by AlienWolfX** [comment]
> I found [this device](https://www.aliexpress.us/item/3256806674518599.html) on AliExpress and looking at the specifications I noticed that it uses the same chip as the USB sticks, So I bought it, dumped the stock firmware (adb is enabled from the factory, but the device is not rooted) and immediately flashed [openstick](https://wvthoog.nl/openstick/). To my surprise it didn't work, I was stuck on the bootloader, so I decided to flash your version of OpenWRT and Voilà! A tiny (not so tiny) battery-powered device that can run OpenWRT for $20!

Woah, now that's fascinating! If you don't mind removing the cover plate, I'd like to know its hardware specs (RAM, ROM etc). Also  does the modem and WiFi work after flashing OpenWRT?

**Comment by samthelion17** [comment]
The WiFi works, the modem... I haven't been able to try it yet 'cause I don't own a SIM card. I will show what's under the shield if it's not soldered but when I checked the build.prop I saw 400something megabytes of RAM, and the firmware dump is about the same size as the original stick so it should have a similar amount of storage. The device runs a version of Android 4.4.4 built on 2024 and the webUI has dramatically improved. Another thing I'd like to try is flash the firmware of this device onto the stick and see if it works.

**Comment by samthelion17** [comment]
> > The device runs a version of Android 4.4.4 built on 2024 and the webUI has dramatically improved.
> 
> Interesting, Can you send me the apk file? I'm interested if there's some changes with the backend code as well.
> 
> Thanks.

I will upload the stock firmware folder with the different partitions to the cloud and paste the link here, that way you can study the new UI better. If that wont work for you just let me know and i'll upload only the apk.

Here's the link: Uploading...

**Comment by AlienWolfX** [comment]
> I will upload the stock firmware folder with the different partitions to the cloud and paste the link here, that way you can study the new UI better.

Thank you! @samthelion17.

**Comment by samthelion17** [comment]
I managed to get openstick working by replacing all .bin files in the 'base' folder with the ones I originally dumped from the device.
