### ISSUE TITLE
Fastboot - dtb not found

### ISSUE THREAD

**Issue by gabronick** [AlienWolfX/UZ801-USB_MODEM#2]
fastboot boot twrp-3.1.1-0-seed.img 
Sending 'boot.img' (22322 KB)                      OKAY [  0.709s]
Booting                                            FAILED (remote: 'dtb not found')
fastboot: error: Command failed

flahed OpenWRT, and it is working, but i can't load TRWP

**Comment by AlienWolfX** [comment]
TWRP is only working with the default android system
