### ISSUE TITLE
Debian Image

### ISSUE THREAD

**Issue by voltrare** [AlienWolfX/UZ801-USB_MODEM#7]
hi, the debian image link is down, do you have the file?

**Comment by AlienWolfX** [comment]
Hello, I've created a temporary link [here](https://drive.google.com/file/d/1mqujlplGCXK3hC5EQKRqMvNC1FBe3loh/view?usp=sharing)

**Comment by voltrare** [comment]
thanks so much i have v3.2 variant do i need to other stuff on it?

**Comment by AlienWolfX** [comment]
> thanks so much i have v3.2 variant do i need to flash other stuff on it? 
> 

No, you don't have to.

**Comment by danyaPostfactum** [comment]
> Download the file using: wget https://download.wvthoog.nlopenstick-uz801-v3.0.zip.

Misspelled link. It should be https://download.wvthoog.nl/openstick-uz801-v3.0.zip

**Comment by danyaPostfactum** [comment]
Do you have  Debian (Based on 5.15 msm8916 mainline) file?
The link http://www-cs-students.stanford.edu/~kaan/test.html is down.
